name: 🐌 Performance
description: File a performance issue
title: "🐌 Performance issue"
labels: ['Type: Performance']
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: input
  id: userid
  attributes:
    label: Userid
    description: The userid
    placeholder: UUID
  validations:
    required: false
- type: input
  id: timestamp
  attributes:
    label: Date & Time
    description: Date and time of found issue
    placeholder: Date & Time
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Evidence
    description: Evidence that shows the issue
    placeholder: |
      1. Screenshot of browser devtools, including GraphQL query, response time
      2. Link/Screenshot to Xray
      3. Link/Screenshot of New Relic/Grafana
  validations:
    required: false
- type: textarea
  attributes:
    label: Device
    description: |
      examples:
         - Device: [e.g. iPhone6]
         - OS: [e.g. iOS]
         - Browser [e.g. chrome, safari]
         - Version [e.g. 22]
    value: |
         - Device: 
         - OS: 
         - Browser
         - Version
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
